name: Android Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  arm64:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type:
          - release

    steps:
    - name: Set BUILD_TYPE variable
      run: echo "BUILD_TYPE=${{ matrix.build_type }}" >> $GITHUB_ENV

    - uses: actions/checkout@v4
    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Deps
      run: |
          sudo add-apt-repository -y ppa:theofficialgman/gpu-tools
          sudo apt-get update -y
          sudo apt-get install ccache glslang-dev glslang-tools apksigner -y

    - name: Set glslang submodule to specific commit
      run: |
          cd externals/glslang  # Navigate to the glslang submodule directory
          git checkout 1e4955adbcd9b3f5eaf2129e918ca057baed6520  # Checkout the specific commit
          cd ../..  # Navigate back to the root of the repository

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DENABLE_SDL2=OFF -DENABLE_SDL2_FRONTEND=OFF -DENABLE_QT=OFF

    - name: Build
      run: |
        # Build the project with CMake
        cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}
        
        # Build the Android app with Gradle
        cd src/android
        ./gradlew assemble${{ env.BUILD_TYPE }}
        ls -R app/build/outputs
        cd ../..

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Android APK
        path: |
          ./src/android/app/build/outputs/apk/canary/${{ env.BUILD_TYPE }}/app-canary-${{ env.BUILD_TYPE }}.apk
