name: Release Workflow

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download/Unzip Windows MSVC Artifact
        run: |
          curl -L -o windows-msvc.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/windows-msvc.zip
          unzip windows-msvc.zip -d ./windows-msvc
          mv ./windows-msvc/lemonade-windows-msvc-*-commit.zip ./windows-msvc.zip

      - name: Download/Unzip Windows MSYS2 Artifact
        run: |
          curl -L -o windows-msys2.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/windows-msys2.zip
          unzip windows-msys2.zip -d ./windows-msys2
          mv ./windows-msys2/lemonade-windows-msys2-*-commit.zip ./windows-msys2.zip

      - name: Download Linux AppImage Artifact
        run: |
          curl -L -o linux-appimage.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/linux-appimage.zip

      - name: Download/Unzip Android APK Artifact
        run: |
          curl -L -o Android-APK.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/Android-APK.zip
          unzip Android-APK.zip -d ./AndroidAPK

      - name: Download Mac OS Artifact
        run: |
          curl -L -o macos-universal.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/macos-universal.zip

      - name: Download Source Artifact
        run: |
          curl -L -o source.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/source.zip
          curl -L -o sha256.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/sha256.zip

      - name: Extract ZIP File
        run: unzip source.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Lemonade ${{ github.run_number }}
          body: |
            Description of the release goes here.
          draft: true
          prerelease: false

      - name: upload Android artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./AndroidAPK/app-canary-release.apk
          asset_name: app-canary-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: upload linux-appimage artifact
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-appimage.zip
          asset_name: linux-appimage.zip
          asset_content_type: application/zip

      - name: upload windows-msvc artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-msvc.zip
          asset_name: windows-msvc.zip
          asset_content_type: application/zip

      - name: upload windows-msys2 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-msys2.zip
          asset_name: windows-msys2.zip
          asset_content_type: application/zip

      - name: upload mac-os artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-universal.zip
          asset_name: macos-universal.zip
          asset_content_type: application/zip

      - name: upload source artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lemonade-unified-source.tar.xz
          asset_name: lemonade-unified-source.tar.xz
          asset_content_type: application/xz

      - name: upload sha256 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTION }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sha256.zip
          asset_name: sha256.zip
          asset_content_type: application/zip

