name: Release Workflow

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Install GitHub CLI
        run: |
          sudo apt update && sudo apt install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTIONS }}
        run: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: Download Windows MSVC Artifact
        uses: actions/download-artifact@v2
        with:
          name: Windows_MSVC
          path: artifacts/windows-msvc.zip

      - name: Download Linux AppImage Artifact
        uses: actions/download-artifact@v2
        with:
          name: Linux_AppImage
          path: artifacts/linux-appimage.zip

      - name: Download Android APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: Android APK
          path: artifacts/Android APK.zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract Artifacts
        run: |
          mkdir extracted
          unzip artifacts/windows-msvc.zip -d extracted/windows-msvc
          unzip artifacts/linux-appimage.zip -d extracted/linux-appimage
          unzip artifacts/Android APK.zip -d extracted/android-apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Lemonade ${{ github.run_number }}
          body: |
            Description of the release goes here.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTIONS }}

      - name: Upload Extracted Files
        env:
          GITHUB_TOKEN: ${{ secrets.LEMONADEACTIONS }}
        run: |
          # Function to upload files in a directory
          upload_files() {
            local directory=$1
            local content_type=$2
            for filepath in extracted/$directory/*; do
              if [ -f "$filepath" ]; then
                filename=$(basename "$filepath")
                echo "Uploading $filename to release..."
                gh release upload ${{ steps.create_release.outputs.tag_name }} "$filepath" --clobber -R ${{ github.repository }} --name "$filename" --content-type "$content_type"
              fi
            done
          }

          # Call the function for each directory with the appropriate content type
          upload_files "windows-msvc" "application/octet-stream"
          upload_files "linux-appimage" "application/octet-stream"
          upload_files "android-apk" "application/vnd.android.package-archive"
