name: Release Workflow

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows MSVC Artifact
        run: |
          curl -L -o windows-msvc.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/windows-msvc.zip

      - name: Download Linux AppImage Artifact
        run: |
          curl -L -o linux-appimage.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/linux-appimage.zip

      - name: Download Android APK Artifact
        run: |
          curl -L -o APK.zip https://nightly.link/Lemonade-emu/Lemonade/workflows/build/master/Android%20APK.zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Extract Artifacts
        run: |
          mkdir extracted
          unzip windows-msvc.zip -d extracted/windows-msvc
          unzip linux-appimage.zip -d extracted/linux-appimage
          unzip Android APK.zip -d extracted/android-apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Lemonade ${{ github.run_number }}
          body: |
            Description of the release goes here.
          draft: true
          prerelease: true
        
      - name: Upload Extracted Files
        run: |
          # Function to upload files in a directory
          upload_files() {
            local directory=$1
            local content_type=$2
            for filepath in extracted/$directory/*; do
              if [ -f "$filepath" ]; then
                filename=$(basename "$filepath")
                echo "Uploading $filename to release..."
                gh release upload ${{ steps.create_release.outputs.tag_name }} "$filepath" --clobber -R ${{ github.repository }} --name "$filename" --content-type "$content_type"
              fi
            done
          }

          # Call the function for each directory with the appropriate content type
          upload_files "windows-msvc" "application/octet-stream"
          upload_files "linux-appimage" "application/octet-stream"
          upload_files "android-apk" "application/vnd.android.package-archive"
